### ISSUE TITLE
拼接url 不要使用 path.join  window上的sep是 \\

### ISSUE THREAD

**Issue by rambo-panda** [IveHD/web-route#1]
https://github.com/IveHD/web-route/blob/master/src/core/route.ts#L82

建议使用 new URL or url.parse

**Comment by rambo-panda** [comment]
建议使用  new URL or url.parse

**Comment by rambo-panda** [comment]
throw new Error(`duplicate interface: ${e.method}: ${url}`);
          
          这里报错  重复的interface 有点不太合理吧。  duplicate route？

**Comment by rambo-panda** [comment]
`map` 应该是一个私有属性，暴露出去有可能会被外界破坏。

**Comment by IveHD** [comment]
已修复、优化。
